#!/usr/bin/env php
<?php
/**
 * Generate docs/database-schema.md from the live SQLite database.
 *
 * Introspects sqlite_master + PRAGMA table_info / foreign_key_list / index_list
 * for every user table, producing a single Markdown reference. This is the real
 * database schema — distinct from docs/schema-quick-reference.md, which documents
 * SEO JSON-LD markup.
 *
 * Run after applying migrations:
 *   php scripts/dump-schema.php
 *
 * Requires DB_PATH (from .env). Exits 0 with a warning if the DB is unavailable
 * so it can be chained safely in `npm run docs:gen`.
 */

if (php_sapi_name() !== 'cli') {
    fwrite(STDERR, "This script must be run from the command line.\n");
    exit(1);
}

require_once __DIR__ . '/../inc/db.php';

try {
    $db = getDB();
} catch (Throwable $e) {
    fwrite(STDERR, "⚠ Skipping schema dump — database unavailable: " . $e->getMessage() . "\n");
    exit(0);
}

$tablesRes = $db->query("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name");
$tables = [];
while ($row = $tablesRes->fetchArray(SQLITE3_ASSOC)) {
    $tables[] = $row['name'];
}

$out = [];
$out[] = "<!-- GENERATED by scripts/dump-schema.php — DO NOT EDIT. Regenerate after migrations: php scripts/dump-schema.php -->";
$out[] = "# Database Schema";
$out[] = "";
$out[] = "Auto-generated reference of the SQLite schema (**" . count($tables) . " tables**).";
$out[] = "The live database is the source of truth; regenerate after every migration with";
$out[] = "`php scripts/dump-schema.php`.";
$out[] = "";
$out[] = "> Not to be confused with `docs/schema-quick-reference.md`, which documents SEO JSON-LD schema markup.";
$out[] = "";
$out[] = "## Tables";
$out[] = "";
foreach ($tables as $name) {
    $out[] = "- [`{$name}`](#" . strtolower(str_replace('_', '-', $name)) . ")";
}
$out[] = "";

foreach ($tables as $name) {
    $out[] = "## {$name}";
    $out[] = "";
    $out[] = "| Column | Type | Null | Default | PK |";
    $out[] = "|--------|------|------|---------|----|";

    $cols = $db->query('PRAGMA table_info("' . $name . '")');
    while ($c = $cols->fetchArray(SQLITE3_ASSOC)) {
        $nn  = $c['notnull'] ? 'NOT NULL' : '';
        $def = $c['dflt_value'] !== null ? '`' . $c['dflt_value'] . '`' : '';
        $pk  = $c['pk'] ? '✓' : '';
        $type = $c['type'] !== '' ? $c['type'] : '—';
        $out[] = "| `{$c['name']}` | {$type} | {$nn} | {$def} | {$pk} |";
    }
    $out[] = "";

    // Foreign keys
    $fks = $db->query('PRAGMA foreign_key_list("' . $name . '")');
    $fkLines = [];
    while ($f = $fks->fetchArray(SQLITE3_ASSOC)) {
        $onDelete = ($f['on_delete'] && $f['on_delete'] !== 'NO ACTION') ? " (ON DELETE {$f['on_delete']})" : '';
        $fkLines[] = "- `{$f['from']}` → `{$f['table']}.{$f['to']}`{$onDelete}";
    }
    if ($fkLines) {
        $out[] = "**Foreign keys:**";
        $out[] = "";
        $out = array_merge($out, $fkLines);
        $out[] = "";
    }

    // Indexes
    $idxs = $db->query('PRAGMA index_list("' . $name . '")');
    $idxLines = [];
    while ($i = $idxs->fetchArray(SQLITE3_ASSOC)) {
        $uniq = $i['unique'] ? 'UNIQUE ' : '';
        $idxCols = [];
        $ii = $db->query('PRAGMA index_info("' . $i['name'] . '")');
        while ($x = $ii->fetchArray(SQLITE3_ASSOC)) {
            $idxCols[] = $x['name'];
        }
        $idxLines[] = "- {$uniq}`{$i['name']}` (" . implode(', ', $idxCols) . ")";
    }
    if ($idxLines) {
        $out[] = "**Indexes:**";
        $out[] = "";
        $out = array_merge($out, $idxLines);
        $out[] = "";
    }
}

$target = APP_ROOT . '/docs/database-schema.md';
file_put_contents($target, implode("\n", $out) . "\n");
echo "✓ Wrote docs/database-schema.md (" . count($tables) . " tables)\n";
