#!/usr/bin/env php
<?php
/**
 * Generate docs/helpers-index.md — a function index for every file in inc/.
 *
 * Uses the PHP tokenizer to list each top-level function with its signature and
 * the first line of its docblock. Lets an agent answer "does a helper for X
 * already exist?" without grepping the 2,000-line helpers.php. Pure filesystem.
 *
 *   php scripts/gen-helpers-index.php
 */

if (php_sapi_name() !== 'cli') {
    fwrite(STDERR, "This script must be run from the command line.\n");
    exit(1);
}

$root   = dirname(__DIR__);
$incDir = $root . '/inc';

/** First meaningful line of a docblock (skips @tags and blanks). */
function hi_docSummary(string $doc): string {
    foreach (preg_split('/\r?\n/', $doc) as $line) {
        $line = trim(preg_replace('/^\s*\*?\s?/', '', $line));
        $line = trim($line, "/* ");
        if ($line !== '' && $line[0] !== '@') {
            return $line;
        }
    }
    return '';
}

function hi_cell(string $s): string {
    return str_replace('|', '\|', trim($s));
}

/** Parse top-level function definitions from a PHP file via the tokenizer. */
function hi_functions(string $path): array {
    $tokens = token_get_all(file_get_contents($path));
    $funcs = [];
    $lastDoc = '';
    $n = count($tokens);

    for ($i = 0; $i < $n; $i++) {
        $tok = $tokens[$i];

        if (is_array($tok)) {
            if ($tok[0] === T_DOC_COMMENT) { $lastDoc = $tok[1]; continue; }
            if ($tok[0] === T_WHITESPACE)  { continue; }
            if ($tok[0] === T_FUNCTION) {
                // Find the function name
                $j = $i + 1;
                while ($j < $n && is_array($tokens[$j]) && $tokens[$j][0] === T_WHITESPACE) $j++;
                if (isset($tokens[$j]) && is_array($tokens[$j]) && $tokens[$j][0] === T_STRING) {
                    $name = $tokens[$j][1];
                    // Capture the parameter list up to the matching paren
                    $sig = '';
                    $depth = 0;
                    for ($k = $j + 1; $k < $n; $k++) {
                        $t = $tokens[$k];
                        $text = is_array($t) ? $t[1] : $t;
                        if ($text === '(') { $depth++; }
                        if ($depth > 0) { $sig .= $text; }
                        if ($text === ')') { $depth--; if ($depth === 0) break; }
                    }
                    $sig = preg_replace('/\s+/', ' ', trim($sig));
                    $funcs[] = [
                        'name'    => $name,
                        'sig'     => $name . $sig,
                        'summary' => $lastDoc !== '' ? hi_docSummary($lastDoc) : '',
                    ];
                }
                $lastDoc = '';
                continue;
            }
            // Any other significant token detaches a pending docblock
            $lastDoc = '';
        } else {
            $lastDoc = '';
        }
    }
    return $funcs;
}

$files = glob($incDir . '/*.php');
sort($files);

$totalFns = 0;
$body = [];
foreach ($files as $path) {
    $funcs = hi_functions($path);
    if (!$funcs) continue;
    $rel = 'inc/' . basename($path);
    $body[] = "## {$rel} (" . count($funcs) . ")";
    $body[] = "";
    $body[] = "| Function | Summary |";
    $body[] = "|----------|---------|";
    foreach ($funcs as $f) {
        $body[] = "| `" . hi_cell($f['sig']) . "` | " . hi_cell($f['summary']) . " |";
        $totalFns++;
    }
    $body[] = "";
}

$out = [];
$out[] = "<!-- GENERATED by scripts/gen-helpers-index.php — DO NOT EDIT. Regenerate: php scripts/gen-helpers-index.php -->";
$out[] = "# Helpers & Core Function Index";
$out[] = "";
$out[] = "Every top-level function defined under `inc/` (**{$totalFns} functions**), grouped by";
$out[] = "file. Check here before writing a new utility — and remember each function name must be";
$out[] = "unique across `inc/` (duplicate declarations cause ERROR 500; `npm run check` guards this).";
$out[] = "";
$out = array_merge($out, $body);

file_put_contents($root . '/docs/helpers-index.md', implode("\n", $out) . "\n");
echo "✓ Wrote docs/helpers-index.md ({$totalFns} functions)\n";
