#!/usr/bin/env php
<?php
/**
 * Generate components/CATALOG.md — an index of every reusable UI component.
 *
 * Extracts each component's leading docblock: title/description and the
 * "Expects:" variable list (components inherit parent PHP scope). Files whose
 * docblock mentions INACTIVE/WIP are flagged. Pure filesystem; no DB/env.
 *
 *   php scripts/gen-component-catalog.php
 */

if (php_sapi_name() !== 'cli') {
    fwrite(STDERR, "This script must be run from the command line.\n");
    exit(1);
}

$root    = dirname(__DIR__);
$compDir = $root . '/components';

function cc_leadingDoc(string $code): ?string {
    return preg_match('/\/\*\*(.*?)\*\//s', $code, $m) ? $m[1] : null;
}

function cc_cleanDoc(?string $raw): array {
    if ($raw === null) return [];
    $lines = array_map(
        fn($l) => rtrim(preg_replace('/^\s*\*?\s?/', '', $l)),
        preg_split('/\r?\n/', $raw)
    );
    while ($lines && $lines[0] === '') array_shift($lines);
    while ($lines && end($lines) === '') array_pop($lines);
    return $lines;
}

function cc_cell(string $s): string {
    return str_replace('|', '\|', trim($s));
}

$files = [];
$it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($compDir, FilesystemIterator::SKIP_DOTS));
foreach ($it as $f) {
    if ($f->isFile() && $f->getExtension() === 'php') {
        $files[] = $f->getPathname();
    }
}
sort($files);

$groups = [];
foreach ($files as $path) {
    $rel = ltrim(str_replace($compDir, '', $path), '/');
    $dir = dirname($rel);
    $dir = $dir === '.' ? '(root)' : $dir;

    $code  = file_get_contents($path);
    $lines = cc_cleanDoc(cc_leadingDoc($code));

    $expects = '';
    $desc = '';
    $wip = false;
    foreach ($lines as $l) {
        if (preg_match('/^Expects:\s*(.+)/i', $l, $m)) {
            $expects = trim($m[1]);
        }
        if (stripos($l, 'INACTIVE') !== false || stripos($l, 'WIP') !== false) {
            $wip = true;
        }
    }
    // description = first line that isn't the Expects line
    foreach ($lines as $l) {
        if ($l !== '' && stripos($l, 'Expects:') !== 0) {
            $desc = $l;
            break;
        }
    }

    $groups[$dir][] = [
        'file'    => basename($rel),
        'expects' => $expects,
        'desc'    => $desc !== '' ? $desc : '_(no docblock)_',
        'wip'     => $wip,
    ];
}

$total = count($files);
$out = [];
$out[] = "<!-- GENERATED by scripts/gen-component-catalog.php — DO NOT EDIT. Regenerate: php scripts/gen-component-catalog.php -->";
$out[] = "# Component Catalog";
$out[] = "";
$out[] = "Index of all **{$total}** PHP components under `components/`. Components are plain";
$out[] = "PHP includes that inherit the parent page's variable scope — the **Expects** column";
$out[] = "lists the variables each one reads. ⚠️ marks inactive / work-in-progress files.";
$out[] = "";

uksort($groups, fn($a, $b) => $a === '(root)' ? -1 : ($b === '(root)' ? 1 : strcmp($a, $b)));

foreach ($groups as $dir => $rows) {
    $heading = $dir === '(root)' ? 'components/' : "components/{$dir}/";
    $out[] = "## {$heading}";
    $out[] = "";
    $out[] = "| Component | Expects | Description |";
    $out[] = "|-----------|---------|-------------|";
    usort($rows, fn($a, $b) => strcmp($a['file'], $b['file']));
    foreach ($rows as $r) {
        $flag = $r['wip'] ? '⚠️ ' : '';
        $expects = $r['expects'] !== '' ? '`' . cc_cell($r['expects']) . '`' : '';
        $out[] = "| {$flag}`{$r['file']}` | {$expects} | " . cc_cell($r['desc']) . " |";
    }
    $out[] = "";
}

file_put_contents($compDir . '/CATALOG.md', implode("\n", $out) . "\n");
echo "✓ Wrote components/CATALOG.md ({$total} components)\n";
