#!/usr/bin/env php
<?php
/**
 * Generate docs/api-manifest.md — an index of every public/api endpoint.
 *
 * Extracts the leading docblock from each endpoint (method, route, summary) and
 * groups them by subdirectory. Pure filesystem; no DB/env required.
 *
 *   php scripts/gen-api-manifest.php
 */

if (php_sapi_name() !== 'cli') {
    fwrite(STDERR, "This script must be run from the command line.\n");
    exit(1);
}

$root   = dirname(__DIR__);
$apiDir = $root . '/public/api';

/** Pull the first /** ... *\/ docblock body out of PHP source. */
function dg_leadingDoc(string $code): ?string {
    return preg_match('/\/\*\*(.*?)\*\//s', $code, $m) ? $m[1] : null;
}

/** Strip ` * ` prefixes and surrounding blank lines from a raw docblock body. */
function dg_cleanDoc(?string $raw): array {
    if ($raw === null) return [];
    $lines = array_map(
        fn($l) => rtrim(preg_replace('/^\s*\*?\s?/', '', $l)),
        preg_split('/\r?\n/', $raw)
    );
    while ($lines && $lines[0] === '') array_shift($lines);
    while ($lines && end($lines) === '') array_pop($lines);
    return $lines;
}

function dg_cell(string $s): string {
    return str_replace('|', '\|', trim($s));
}

// Collect endpoint files
$files = [];
$it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($apiDir, FilesystemIterator::SKIP_DOTS));
foreach ($it as $f) {
    if ($f->isFile() && $f->getExtension() === 'php') {
        $files[] = $f->getPathname();
    }
}
sort($files);

// Group by directory relative to public/api
$groups = [];
foreach ($files as $path) {
    $rel = ltrim(str_replace($apiDir, '', $path), '/');
    $dir = dirname($rel);
    $dir = $dir === '.' ? '(root)' : $dir;

    $code  = file_get_contents($path);
    $lines = dg_cleanDoc(dg_leadingDoc($code));

    $route = '';
    $summary = '';
    foreach ($lines as $l) {
        if ($route === '' && preg_match('/\b(GET|POST|PUT|DELETE|PATCH)\b\s+\/\S+/i', $l, $m)) {
            $route = trim($m[0]);
        }
    }
    foreach ($lines as $l) {
        $cand = preg_replace('/^API:\s*/i', '', $l);
        if ($cand !== '' && !preg_match('/\b(GET|POST|PUT|DELETE|PATCH)\b\s+\//i', $cand)
            && stripos($cand, 'param') !== 0 && stripos($cand, 'body') !== 0) {
            $summary = $cand;
            break;
        }
    }

    $groups[$dir][] = [
        'file'    => basename($rel),
        'route'   => $route,
        'summary' => $summary !== '' ? $summary : ($lines ? $lines[0] : '_(no docblock)_'),
    ];
}
ksort($groups);

$total = count($files);
$out = [];
$out[] = "<!-- GENERATED by scripts/gen-api-manifest.php — DO NOT EDIT. Regenerate: php scripts/gen-api-manifest.php -->";
$out[] = "# API Manifest";
$out[] = "";
$out[] = "Index of all **{$total}** endpoints under `public/api/`. Most return HTML when the";
$out[] = "`HX-Request` header is present and JSON otherwise (`isHtmx()` / `?format=`).";
$out[] = "Open the file for full request/response details.";
$out[] = "";

// Stable, readable group order: root first, then alphabetical
uksort($groups, fn($a, $b) => $a === '(root)' ? -1 : ($b === '(root)' ? 1 : strcmp($a, $b)));

foreach ($groups as $dir => $rows) {
    $heading = $dir === '(root)' ? 'public/api/' : "public/api/{$dir}/";
    $out[] = "## {$heading}";
    $out[] = "";
    $out[] = "| Endpoint | Route | Summary |";
    $out[] = "|----------|-------|---------|";
    usort($rows, fn($a, $b) => strcmp($a['file'], $b['file']));
    foreach ($rows as $r) {
        $route = $r['route'] !== '' ? '`' . dg_cell($r['route']) . '`' : '';
        $out[] = "| `{$r['file']}` | {$route} | " . dg_cell($r['summary']) . " |";
    }
    $out[] = "";
}

file_put_contents($root . '/docs/api-manifest.md', implode("\n", $out) . "\n");
echo "✓ Wrote docs/api-manifest.md ({$total} endpoints)\n";
